### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by lizsdswsd** [dimdenGD/LastFMRichPresence#8]
as its released, i was getting problems. when will it be fixed?

**Comment by dimdenGD** [comment]
Do you get any errors in devtools console (CTRL+SHIFT+I) from plugin? You can search `lastfm` in console filter to see

**Comment by lizsdswsd** [comment]
yes, i do get errors
![Screenshot 2023-05-25 004350](https://github.com/dimdenGD/LastFMRichPresence/assets/130219109/89a9061b-fced-452b-892a-5ea5137372e4)

**Comment by dimdenGD** [comment]
Seems like you've setup lastfm wrong

**Comment by lizsdswsd** [comment]
hmm.. how do i set up the lastfm? im sure i followed the steps that was there...

**Comment by dimdenGD** [comment]
Make sure you've pasted key correctly and wrote correct username

**Comment by dimdenGD** [comment]
you need webscrobbler browser extension for youtube music to show up

**Comment by lizsdswsd** [comment]
it still doesnt work.. huh idk what i did...
